apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-chart
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{.Values.ports.MONGO_PORT}}
          name: db
        