apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongo-chart
  namespace: sympho-ns
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../charts/mongo/
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    ports:
      MONGO_PORT: 27017
      