apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodejs-chart
  namespace: sympho-api-ns
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../charts/sympho-api/
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
