apiVersion: v1
kind: Service
metadata:
  name: sympho-svc-chart
  labels:
    name: sympho-api
    app: sympho-api
spec:
  selector:
    app: sympho-api
  ports:
  - name: sympho-api
    port: 80
    targetPort: {{.Values.ports.API_PORT}}
  
