apiVersion: v1
kind: Service
metadata:
  name: dso-gke-nodejs-svc-chart
  labels:
    name: dso-gke-nodejs
    app: api-nodejs
spec:
  selector:
    app: dso-gke-nodejs
  ports:
  - name: dso-gke-nodejs
    port: 80
    targetPort: {{.Values.ports.API_PORT}}
  - name: prometheus
    port: {{.Values.ports.PROMETHEUS_PORT}}
    targetPort: {{.Values.ports.PROMETHEUS_PORT}}
